/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package owl_wizard;

import java.util.*;

/**
 *
 * @author shsu
 */
public class Complexity extends javax.swing.JPanel {

    /**
     * Creates new form WhatLanguage
     */
    
    ArrayList<Candidate> candidates; 
    
    public Complexity(ArrayList<Candidate> cand) {
        
        candidates = cand;
        
        initComponents();
   
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        pTime = new javax.swing.JCheckBox();
        nExpTime = new javax.swing.JCheckBox();
        coNpComplete = new javax.swing.JCheckBox();
        nLogspaceComplete = new javax.swing.JCheckBox();

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel2.setText("Computational Dealbreakers?");

        pTime.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        pTime.setText("Polynomial time [O(p(n))] complete");
        pTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pTimeActionPerformed(evt);
            }
        });

        nExpTime.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        nExpTime.setText("Exponential polynomial  time [ O(2^p(n)) ] complete");
        nExpTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nExpTimeActionPerformed(evt);
            }
        });

        coNpComplete.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        coNpComplete.setText("Complement of problem is NP-complete");
        coNpComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coNpCompleteActionPerformed(evt);
            }
        });

        nLogspaceComplete.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        nLogspaceComplete.setText("NLogspace-complete");
        nLogspaceComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nLogspaceCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel2)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nLogspaceComplete)
                    .addComponent(coNpComplete)
                    .addComponent(nExpTime)
                    .addComponent(pTime, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(pTime)
                .addGap(49, 49, 49)
                .addComponent(nExpTime)
                .addGap(49, 49, 49)
                .addComponent(coNpComplete)
                .addGap(49, 49, 49)
                .addComponent(nLogspaceComplete)
                .addContainerGap(202, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pTimeActionPerformed
        // TODO add your handling code here:
        
        if (pTime.isSelected())
           candidates.get(1).weighting -= 2;
        if (!pTime.isSelected())
           candidates.get(1).weighting += 2;
        
    }//GEN-LAST:event_pTimeActionPerformed

    private void nExpTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nExpTimeActionPerformed
        // TODO add your handling code here:
        if (nExpTime.isSelected())
           candidates.get(0).weighting -= 2;
        if (!nExpTime.isSelected())
           candidates.get(0).weighting += 2;
        
    }//GEN-LAST:event_nExpTimeActionPerformed

    private void coNpCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coNpCompleteActionPerformed
        // TODO add your handling code here:
        if (coNpComplete.isSelected())
           candidates.get(3).weighting -= 2;
        if (!coNpComplete.isSelected())
           candidates.get(3).weighting += 2;
    }//GEN-LAST:event_coNpCompleteActionPerformed

    private void nLogspaceCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nLogspaceCompleteActionPerformed
        // TODO add your handling code here:
        if (nLogspaceComplete.isSelected())
           candidates.get(2).weighting -= 2;
        if (!nLogspaceComplete.isSelected())
           candidates.get(2).weighting -= 2;
        
    }//GEN-LAST:event_nLogspaceCompleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox coNpComplete;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox nExpTime;
    private javax.swing.JCheckBox nLogspaceComplete;
    private javax.swing.JCheckBox pTime;
    // End of variables declaration//GEN-END:variables
}
