/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package owl_wizard;

import java.util.*;

import javax.swing.*;
import java.awt.*;

import com.google.common.collect.Sets;
/**
 *
 * @author shsu
 */

public class FeatureSelector extends javax.swing.JPanel {

    /**
     * Creates new form FeatureSelector
     */
    
    JCheckBox[] checkboxes;
    
    TreeSet<String> desired, dl, el, ql, rl, questions;
    
    ArrayList<Candidate> topChoices;
    
    JPanel nextPanel;
    
    public FeatureSelector(ArrayList<Candidate> choices, TreeSet<String> d, TreeSet<String> e, TreeSet<String> q, TreeSet<String> r) 
    {
        dl = d;
        el = e;
        ql = q;
        rl = r;
        choices = topChoices;
        
        initComponents();
        
        desired = (TreeSet<String>) dl.clone();
        
        checkboxes = new JCheckBox[dl.size()];
        
        Object[] dl_constructs = dl.toArray();
        
        
        //make checkboxes from list of dl constructs
        for (int i = 0 ; i < checkboxes.length; i++)
        {
            checkboxes[i] = new JCheckBox((String) dl_constructs[i], false);          
        }
        
        GridLayout experimentLayout = new GridLayout(35,2);

        
        this.setLayout(experimentLayout);
        
        JLabel title = new JLabel ("Tick all the features you need:");
        title.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
          
        add(title);

        for (int i = 0 ; i < 1; i++)
            add(new Filler());
        
        for (int i = 0; i < checkboxes.length; i++)
            add(checkboxes[i]);
  
        
        topChoices = new ArrayList<Candidate>();
  
                
    }
    
    //remove all the unselected constructs from the list
    public void tally ()
    {
        for (int i = 0; i < checkboxes.length; i++)
        {
            
            if (!checkboxes[i].isSelected())
            {
                desired.remove(checkboxes[i].getText());
            }
            
        }
    }
    
    //now calculate the set of constructs with the smallest distance to our desired construct list
    public void preferences ()
    {
        
//        Set dl_diff = Sets.difference(desired, dl);
//        Set el_diff = Sets.difference(desired, el);
//        Set ql_diff = Sets.difference(desired, ql);
//        Set rl_diff = Sets.difference(desired, rl);
        
        dl.retainAll(desired);
        el.retainAll(desired);
        ql.retainAll(desired);
        rl.retainAll(desired);
        
        //topChoices.put(dl.size(), "OWL2-DL");
        topChoices.add(new Candidate("OWL2-EL", el.size()));
        topChoices.add(new Candidate("OWL2-QL", ql.size()));
        topChoices.add(new Candidate("OWL2-RL", rl.size()));
              
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    class Filler extends JLabel
    {
        Filler ()
        {
            super();
            setOpaque(false);
            setVisible(false);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
