/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package owl_wizard;

import javax.swing.JOptionPane;
import java.util.*;

/**
 *
 * @author shsu
 */
public class OWL_Wizard extends javax.swing.JFrame {

    /**
     * Creates new form OWL_Wizard
     */
    
    
    //Store all the possible languages here
    
    
    
    
    public OWL_Wizard() {
        initComponents();
    }
    
    TreeMap< String, LinkedList<String> > candidates = new TreeMap();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(startButton)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(startButton)
                .addGap(162, 162, 162))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        
        
        candidates.put("OWL", new LinkedList<String>());
        candidates.put("OWL2", new LinkedList<String>());
        
        candidates.get("OWL").add("OWL Full");
        candidates.get("OWL").add("OWL DL");
        candidates.get("OWL").add("OWL Lite");
        
        candidates.get("OWL2").add("OWL2 DL");
        candidates.get("OWL2").add("OWL2-EL");
        candidates.get("OWL2").add("OWL2-QL");
        candidates.get("OWL2").add("OWL2-RL");
        candidates.get("OWL2").add("OWL2 Full");
       

        
        //Choose between OWL and OWL2-DL
        int answer = JOptionPane.showConfirmDialog(this, "Do you need any one of the following constructs:"
                + "\n - Qualified Cardinality" 
                + "\n - Property propagation over transitive relationships"
                + "\n - Properties of properties"
                + "\n - Range-restricted data properties"
                + "\n - Aggregation Functions"
                + "\n - Primary key constraints on data properties"
                + "\n - Binary relationships between data properties on the same object");
        
        
        if (answer == JOptionPane.YES_OPTION)
                candidates.remove("OWL");    
                
        
        answer = JOptionPane.showConfirmDialog(this, "Do you need any one of the following constructs?"
            + "\n - Disjunction"
            + "\n - Cardinality Restrictions");
        
        
        if (answer == JOptionPane.YES_OPTION)
        {
            candidates.get("OWL2").remove("OWL2-QL");
            candidates.get("OWL2").remove("OWL2-EL");
        }
        
        
        
        
        answer = JOptionPane.showConfirmDialog(this, "Do you wish to use a reasoner on your ontology?");
        
        if (answer == JOptionPane.YES_OPTION)
        {
            candidates.get("OWL").remove("OWL Full");
            candidates.get("OWL2").remove("OWL2 Full");
        }
        
        
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OWL_Wizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OWL_Wizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OWL_Wizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OWL_Wizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OWL_Wizard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
