/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package owl_wizard;

import javax.swing.JOptionPane;
import java.util.*;
import java.io.*;




/**
 *
 * @author shsu
 */
public class OWL_Wizard extends javax.swing.JFrame {

    /**
     * Creates new form OWL_Wizard
     */
    
    
    //Store all the possible languages here
    
    TreeSet<String> owl2_dl;
    TreeSet<String> owl2_rl;
    TreeSet<String> owl2_ql;
    TreeSet<String> owl2_el;
    
    
    public OWL_Wizard() {
        initComponents();
    }
    
    TreeMap< String, LinkedList<String> > candidates = new TreeMap();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1101, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, "card1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //read in all the language feature constructs
    private void readFile ()
    { 
      System.out.println(System.getProperty("user.dir"));
      
      owl2_dl = new TreeSet<String>();
      owl2_rl = new TreeSet<String>();      
      owl2_ql = new TreeSet<String>();
      owl2_el = new TreeSet<String>();
      
        try
        {
         Scanner scan = new Scanner (new File(System.getProperty("user.dir") + "/txt/OWL2-DL"));
         
         String category = "";
         
         //add each construct to the set for this species, appended with the category under which it belongs
         while (scan.hasNextLine())
         {
             String line = scan.nextLine();
             
             if (line.trim().equals("") && scan.hasNextLine())
                category = scan.nextLine();
             else
             {
                 owl2_dl.add(category + " " + line);
             }
             
         }
         
         
         scan = new Scanner (new File (System.getProperty("user.dir") + "/txt/OWL2-EL"));
         
         //add each construct to the set for this species, appended with the category under which it belongs
         while (scan.hasNextLine())
         {
             String line = scan.nextLine();
             
             if (line.trim().equals("") && scan.hasNextLine())
                category = scan.nextLine();
             else
                owl2_el.add(category + " " + line);
             
         }
         
         
         scan = new Scanner (new File (System.getProperty("user.dir") + "/txt/OWL2-QL"));
         
         //add each construct to the set for this species, appended with the category under which it belongs
         while (scan.hasNextLine())
         {
             String line = scan.nextLine();
             
             if (line.trim().equals("") && scan.hasNextLine())
                category = scan.nextLine();
             else
                owl2_ql.add(category + " " + line);
             
         }
         
         scan = new Scanner (new File (System.getProperty("user.dir") + "/txt/OWL2-RL"));
         
         //add each construct to the set for this species, appended with the category under which it belongs
         while (scan.hasNextLine())
         {
             String line = scan.nextLine();
             
             if (line.trim().equals("") && scan.hasNextLine())
                category = scan.nextLine();
             else
                owl2_rl.add(category + " " + line);
             
         }         
                 
         
        }
        catch (FileNotFoundException f)
        {
            System.out.println("File Not Found.");
            System.exit(0);
            
        }
        
        
        
        
    }
    

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OWL_Wizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OWL_Wizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OWL_Wizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OWL_Wizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OWL_Wizard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
