/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package owl_wizard;

import java.util.*;

/**
 *
 * @author shsu
 */
public class WhatConcepts extends javax.swing.JPanel {

    /**
     * Creates new form WhatConcepts
     */
    
    ArrayList<Candidate> candidates; 
    
    public WhatConcepts(ArrayList<Candidate> cand) {
        
        candidates = cand;
        
        initComponents();
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nestedClasses = new javax.swing.JCheckBox();
        instances = new javax.swing.JCheckBox();
        relationships = new javax.swing.JCheckBox();

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("What will your ontology feature heavily?");

        nestedClasses.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        nestedClasses.setText("Classes and nested classes");
        nestedClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nestedClassesActionPerformed(evt);
            }
        });

        instances.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        instances.setText("Instances and individuals");
        instances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instancesActionPerformed(evt);
            }
        });

        relationships.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        relationships.setText("Complex relationships");
        relationships.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationshipsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(relationships)
                            .addComponent(nestedClasses)
                            .addComponent(instances))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(nestedClasses)
                .addGap(37, 37, 37)
                .addComponent(instances)
                .addGap(36, 36, 36)
                .addComponent(relationships)
                .addContainerGap(282, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nestedClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nestedClassesActionPerformed

        
        if (nestedClasses.isSelected())
           candidates.get(1).weighting += 2;
        if (!nestedClasses.isSelected())
           candidates.get(1).weighting -= 2;
        
        
        if (nestedClasses.isSelected() && instances.isSelected() && relationships.isSelected())
           candidates.get(0).weighting += 2;
        else
            candidates.get(0).weighting -= 2;        
    }//GEN-LAST:event_nestedClassesActionPerformed

    private void instancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instancesActionPerformed

        if (instances.isSelected())
           candidates.get(2).weighting += 2;
        if (!instances.isSelected())
           candidates.get(2).weighting -= 2;
        
        if (nestedClasses.isSelected() && instances.isSelected() && relationships.isSelected())
           candidates.get(0).weighting += 2;
        else
            candidates.get(0).weighting -= 2;      
        
    }//GEN-LAST:event_instancesActionPerformed

    private void relationshipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationshipsActionPerformed

        if (relationships.isSelected())
           candidates.get(0).weighting += 2;
        if (!relationships.isSelected())
           candidates.get(0).weighting -= 2;
        
        if (nestedClasses.isSelected() && instances.isSelected() && relationships.isSelected())
           candidates.get(0).weighting += 2;
        else
            candidates.get(0).weighting -= 2;     
        
    }//GEN-LAST:event_relationshipsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox instances;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox nestedClasses;
    private javax.swing.JCheckBox relationships;
    // End of variables declaration//GEN-END:variables
}
